### ISSUE TITLE
Unable to connect Ghost running container from Nginx

### ISSUE THREAD

**Issue by robincher** [jwasham/docker-ghost-template#5]
Hi John,

I was checking out how i could install ghost, and came across your neat docker compose template.TL:DR , i didn't proceed with the ghost cli option due to networking policy within my place, and thought dockers is something i can look into.

I managed to run the docker-compose without issues, and all 3 containers start as expected.

Somehow, whenever i try to access ghost admin **(http://myhost.com),** i will get a 502 Bad Gateway error.  Seems like the nginx container have issues connecting to ghost container.

Do i need to further configure nginx ?

- /etc/nginx/sites-available
- /etc/nginx/sites-enabled

```
2018/01/17 08:29:30 [error] 5#5: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.181.118, server: myhost.com, request: "GET /ghost/ HTTP/1.1", upstream: "http://172.19.0.3:2368/ghost/", host: "myhost.com"
```

**default conf snippets**
```

upstream ghost-upstream{
  server ghost:2368;
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ghost.domain.dev;

    ssl_certificate /etc/nginx/ssl/ghost.domain.dev;.crt;
    ssl_certificate_key /etc/nginx/ssl/ ghost.domain.dev;.key;

    location / {
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header HOST $http_host;
       proxy_set_header X-NginX-Proxy true;
       proxy_set_header X-Forwarded-Proto $scheme;

       proxy_pass http://ghost-upstream:2368;
       proxy_redirect off;
    }

    location ~ /\. { deny  all; access_log off; log_not_found off; }
}
```
**Docker Compose snippets**
```
nginx:
  container_name: nginx
  build: ./nginx
  volumes:
    - ./nginx/volumes/ssl:/etc/nginx/ssl:z
  ports:
    - "80:80"
    - "443:443"
  links:
    - ghost
  restart: always

ghost:
  container_name: ghost
  volumes:
    - ./ghost/volumes/content:/var/lib/ghost/content:z
    - ./ghost/volumes/config.js:/var/lib/ghost/config.js:z
  build: ./ghost
  expose:
    - "2368" # makes it reachable by linked services but unreachable from host for security
  environment: # this section can be commented to start in dev mode by default
    - NODE_ENV=production
    - WEB_DOMAIN=myhost.com
    - DB_DATABASE=ghostdata
    - DB_USER=xxx
    - "DB_PASSWORD=xxx"
  restart: always
  links:
    - mysql
```

Running RHEL 5.7
Docker version : 1.12.6,
Nginx Version : 1.13
MySql Version : 5.7
Ghost Version : 1.2

Thanks!

**Comment by jwasham** [comment]
Sorry for the late reply.

I think the problem is because my setup is based on SSL. 
From docs: "Set the blog domain (server_name) in nginx/copy/default.conf (must match the common name in your SSL certificate)"

**Comment by robincher** [comment]
Hi @jwasham ,

Thanks for the advice. I also made some further modification on the compose file and your project, and it's now working fine.

1) Update the nginx service , and pull the latest nginx image
```
nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/ssl/yourhost.xyz.key:/etc/nginx/yourhost.xyz.key:ro
      - ./nginx/ssl/yourhost.xyz.crt:/etc/nginx/yourhost.xyz.crt:ro
      - ./nginx/conf/ghost.conf:/etc/nginx/conf.d/ghost.conf:z
    links:
      - ghost
    restart: always
```

2) Update the ghost service, and pull latest ghost image
```
ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - ./ghost/config.js:/var/lib/ghost/config.js:z  #Overwrite default setting to use mysql
      - ./ghost/content:/var/lib/ghost/content:z
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=production
      - WEB_DOMAIN=yourhost.xyz
      - DB_DATABASE=ghostdata
      - DB_USER=ghostusr
      - DB_PASSWORD=xyz #please change this
    restart: always
    links:
      - mysql
```
Additionally, there seems to be a bug with the latest Ghost image, so whenever i set up the compose file, i still gotta do a ```docker restart <<ghost service name>>``` to ensure the ghost container is running as expected.

Lastly, thanks for your work, it really helps for folks like us that are running on a restricted network where  there are challenges getting the ghost-cli :).  I'll close the issue now.

Cheers!
Robin
